### ISSUE TITLE
7239 DEV Automate subscritionSettings/options

### ISSUE THREAD

**Issue by deepikasl** [Shippable/bat#164]
https://github.com/Shippable/pm/issues/7239

**testSuite1**: Technical Contact Edit Button
![screenshot from 2016-11-28 08 54 40](https://cloud.githubusercontent.com/assets/18304961/20655429/5c57e1ca-b548-11e6-84d1-f183d7c33d14.png)

**testSuite2**: Billing Contact Edit Button
![screenshot from 2016-11-28 08 55 49](https://cloud.githubusercontent.com/assets/18304961/20655444/8107907e-b548-11e6-80c1-7d50be0d1b51.png)

**testSuite3**: Reset Subscription
![screenshot from 2016-11-28 08 56 45](https://cloud.githubusercontent.com/assets/18304961/20655457/a060c54e-b548-11e6-8270-b66bb19d9fe6.png)

**Comment by nranjanShippable** [comment]
this is done.
