### ISSUE TITLE
7239 DEV Automate subscriptionIntegartions/Encrypt

### ISSUE THREAD

**Issue by deepikasl** [Shippable/bat#167]
https://github.com/Shippable/pm/issues/7239

**testSuite1**: Encrypt
![screenshot from 2016-11-28 09 02 45](https://cloud.githubusercontent.com/assets/18304961/20655535/7348fc92-b549-11e6-8450-1288f58e8e32.png)

**testSuite2**: Decrypt
![screenshot from 2016-11-28 09 03 25](https://cloud.githubusercontent.com/assets/18304961/20655545/8a1e0430-b549-11e6-8895-38cf1f996135.png)

**Comment by nranjanShippable** [comment]
This is done.
